export const type = {
    ADD:"ADD",
    CHANGE_TITLE:"CHANGE_TITLE",
    WITH_PARAMS:"WITH_PARAMS",
    VALUE:"VALUE",
    DELETE:"DELETE",
    PLUS:"PLUS",
    MINE:"MINE",
    MULTIPLY:"MULTIPLY",
    DIVIDE:"DIVIDE",
    USERS:"USERS"


}